#!/usr/bin/env bash
set -euo pipefail

marker_start='# >>> agent-tweaks: codex-hold-to-dictate >>>'
marker_end='# <<< agent-tweaks: codex-hold-to-dictate <<<'
script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
source_file="$script_dir/codex_hold_to_dictate.py"
shared_file="$script_dir/../../../shared/codex/hold-to-dictate/dictation_core.py"
data_home="${XDG_DATA_HOME:-$HOME/.local/share}"
config_home="${XDG_CONFIG_HOME:-$HOME/.config}"
bin_home="${HOME}/.local/bin"
install_dir="$data_home/agent-tweaks/codex-hold-to-dictate"
shell_config="$config_home/agent-tweaks/codex-hold-to-dictate.sh"
model_name='vosk-model-small-en-us-0.15'
model_dir="$data_home/agent-tweaks/models/$model_name"
model_url='https://alphacephei.com/vosk/models/vosk-model-small-en-us-0.15.zip'

fail() {
    printf 'error: %s\n' "$*" >&2
    exit 1
}

[[ -f "$source_file" ]] || fail "implementation not found: $source_file"
[[ -f "$shared_file" ]] || fail "shared core not found: $shared_file"
command -v python3 >/dev/null 2>&1 || fail 'Python 3.10 or newer is required.'
python3 -c 'import sys; raise SystemExit(sys.version_info < (3, 10))' \
    || fail 'Python 3.10 or newer is required.'
python3 -c 'import vosk' >/dev/null 2>&1 \
    || fail 'The Python Vosk package is required (Arch: pkexec pacman -S python-vosk).'
command -v pw-cat >/dev/null 2>&1 \
    || fail 'pw-cat is required (install the PipeWire tools for your distribution).'

real_codex="$(command -v codex || true)"
[[ -n "$real_codex" ]] || fail 'Codex CLI must be installed before this tweak.'
case "$real_codex" in
    "$bin_home/codex-hold-to-dictate"|"$bin_home/codex-ptt")
        [[ -n "${AGENT_TWEAKS_CODEX_BIN:-}" ]] \
            || fail 'Could not locate the unwrapped Codex executable.'
        real_codex="$AGENT_TWEAKS_CODEX_BIN"
        ;;
esac

install -Dm755 -- "$source_file" "$install_dir/codex-hold-to-dictate"
install -Dm644 -- "$shared_file" "$install_dir/dictation_core.py"
mkdir -p -- "$bin_home"
ln -sfn -- "$install_dir/codex-hold-to-dictate" "$bin_home/codex-hold-to-dictate"
ln -sfn -- "$install_dir/codex-hold-to-dictate" "$bin_home/codex-ptt"

if [[ ! -d "$model_dir" && ! -d "$HOME/.config/vosk-models/$model_name" ]]; then
    command -v curl >/dev/null 2>&1 || fail 'curl is required to download the Vosk model.'
    command -v unzip >/dev/null 2>&1 || fail 'unzip is required to unpack the Vosk model.'
    temp_dir="$(mktemp -d -t agent-tweaks-model.XXXXXX)"
    trap 'rm -rf -- "$temp_dir"' EXIT
    printf 'Downloading the local English speech model...\n'
    curl -fL --progress-bar -- "$model_url" -o "$temp_dir/model.zip"
    unzip -q -- "$temp_dir/model.zip" -d "$temp_dir"
    mkdir -p -- "$(dirname -- "$model_dir")"
    mv -- "$temp_dir/$model_name" "$model_dir"
fi

mkdir -p -- "$(dirname -- "$shell_config")"
{
    printf '# Generated by Agent Tweaks. Re-run install.sh to update.\n'
    printf 'export AGENT_TWEAKS_CODEX_BIN=%q\n' "$real_codex"
    printf 'alias codex=%q\n' "$bin_home/codex-hold-to-dictate"
    printf 'alias codex-real=%q\n' "$real_codex"
} > "$shell_config"

case "${SHELL##*/}" in
    zsh) shell_rc="$HOME/.zshrc" ;;
    bash|*) shell_rc="$HOME/.bashrc" ;;
esac

touch -- "$shell_rc"
if ! grep -Fq -- "$marker_start" "$shell_rc"; then
    cp -- "$shell_rc" "$shell_rc.agent-tweaks.bak"
    quoted_shell_config="$(printf '%q' "$shell_config")"
    {
        printf '\n%s\n' "$marker_start"
        printf '[[ -r %s ]] && . %s\n' "$quoted_shell_config" "$quoted_shell_config"
        printf '%s\n' "$marker_end"
    } >> "$shell_rc"
fi

printf '\nInstalled Codex hold-to-dictate.\n'
printf 'Open a new terminal, run codex, then hold Space while speaking.\n'
printf 'Use codex-real to bypass the tweak.\n'
